POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de JavaScript"
}

###

GET http://localhost:3333/courses?orderBy=title

###

GET http://localhost:3333/courses/c5633c16-59ec-42e7-99b7-b02d8264056c

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
    "email": "MariaCecilia98@bol.com.br",
    "password": "123456"
}